language: node_js
node_js:
  - "node"

cache: npm

script: npm run bc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: code