os:
  - linux
language: node_js
dist: xenial
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages
  strategy: git
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: code
